
  name: clone_music_player_app
  description: "A new Flutter project."
  publish_to: 'none' # Prevent accidental publishing to pub.dev

  version: 1.0.0+1

  environment:
    sdk: '>=3.4.3 <4.0.0'

  dependencies:
    flutter:
      sdk: flutter
    cupertino_icons: ^1.0.6
    cached_network_image: ^3.2.2
    audio_video_progress_bar: ^0.11.0
    just_audio: ^0.9.30
    just_audio_background: ^0.0.1-beta.7
    audio_service: ^0.18.13
    flutter_local_notifications: ^8.2.0
    marquee: ^2.2.3
  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^3.0.0

  flutter:
    uses-material-design: true

    assets:
      - assets/audio/
      - assets/images/